---
title: "Mapping the Shark research"
author: "Philippe Mongeon"
date: "2020-12-07"
abstract: ""
output: 
  html_document:
    toc: true # adds table on content
    toc_float: true # makes table of content float on the left of the page rather than being at the top of the page
    toc_depth: 3  # up to N depths of headings in the TOC (specified by #, ## and ###)
    number_sections: true # will automatically number your headings
    theme: cosmo  # many options for theme, this one is my favorite.
    highlight: tango  # specifies the syntax highlighting style
#    css: my.css   # you can add your custom css, should be in same folder
---

# Data collection

```{css, echo=FALSE}

# Just to format the page... code won't be displayed because of echo = FALSE

h1 {
  padding-top: 30px;
}
h2 {
  padding-top: 20px;
}
h3{
  padding-top:10px;
}
```

# Mapping the Shark-related scholarship

```{r setup, include=FALSE}
# This code won't be ran because of include = FALSE
```

# Community detection


```{r html table, echo=FALSE, warning=FALSE}
# code will run but will not be displayed
# warnings won't be shown in the output
```

# Topic modelling

```{sql eval=FALSE, echo=TRUE}
# this code will not run but will be displayed"
```

# Bibliometric indicators

# Altmetric indicators




